// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOgVwnw3eq3AHkK--tS3MPligMeaRsCQ',
    appId: '1:481153505959:web:ffdd1751000cb8775a5982',
    messagingSenderId: '481153505959',
    projectId: 'blossomvalley-9b49d',
    authDomain: 'blossomvalley-9b49d.firebaseapp.com',
    storageBucket: 'blossomvalley-9b49d.firebasestorage.app',
    measurementId: 'G-SYJZQLC32B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwZk-3r2iNUzvT08WExtWIZKj2EWUa4N4',
    appId: '1:481153505959:android:ea435684756f243f5a5982',
    messagingSenderId: '481153505959',
    projectId: 'blossomvalley-9b49d',
    storageBucket: 'blossomvalley-9b49d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFwrO_k5aPSbsdmyvaVfPG2YxcUIgjOM',
    appId: '1:481153505959:ios:1c42b4a61659142c5a5982',
    messagingSenderId: '481153505959',
    projectId: 'blossomvalley-9b49d',
    storageBucket: 'blossomvalley-9b49d.firebasestorage.app',
    iosBundleId: 'com.example.blossomvalley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHFwrO_k5aPSbsdmyvaVfPG2YxcUIgjOM',
    appId: '1:481153505959:ios:1c42b4a61659142c5a5982',
    messagingSenderId: '481153505959',
    projectId: 'blossomvalley-9b49d',
    storageBucket: 'blossomvalley-9b49d.firebasestorage.app',
    iosBundleId: 'com.example.blossomvalley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxOgVwnw3eq3AHkK--tS3MPligMeaRsCQ',
    appId: '1:481153505959:web:74b698e19fff0bd35a5982',
    messagingSenderId: '481153505959',
    projectId: 'blossomvalley-9b49d',
    authDomain: 'blossomvalley-9b49d.firebaseapp.com',
    storageBucket: 'blossomvalley-9b49d.firebasestorage.app',
    measurementId: 'G-MG0J0PP8JX',
  );

}